"""The 69 terms and nine categories from Supplemental Table 1 (ztaf119)."""

TERMS = {
    "Sinus rhythm": (
        "sinus rhythm",
    ),
    "ECG measurements / patterns": (
        "left axis deviation",
        "prolonged qt interval",
        "low voltage qrs",
        "st elevation",
        "nonspecific st abnormality",
        "right axis deviation",
        "early repolarization",
        "indeterminate axis",
        "st depression",
    ),
    "Abnormal rhythms": (
        "sinus tachycardia",
        "sinus bradycardia",
        "atrial fibrillation",
        "junctional rhythm",
        "atrial flutter",
        "supraventricular tachycardia",
        "wide qrs tachycardia",
        "idioventricular rhythm",
        "narrow qrs tachycardia",
        "ventricular tachycardia",
        "ectopic atrial rhythm",
    ),
    "Premature beats": (
        "premature ventricular complexes",
        "premature atrial complexes",
        "fusion complexes",
        "supraventricular complexes",
    ),
    "Conduction disorders": (
        "right bundle branch block",
        "1st degree av block",
        "nonspecific intraventricular block",
        "left anterior fascicular block",
        "left bundle branch block",
        "wide qrs rhythm",
        "bifascicular block",
        "aberrant conduction",
        "left posterior fascicular block",
        "2nd degree av block",
        "complete heart block",
        "wpw pattern",
        "av dissociation",
        "complete av block",
    ),
    "Ischemia related": (
        "inferior infarct",
        "anterior infarct",
        "septal infarct",
        "acute mi",
        "lateral infarct",
        "anterolateral infarct",
        "anteroseptal infarct",
        "stemi",
        "posterior infarct",
        "lateral injury pattern",
        "inferior injury pattern",
        "inferolateral injury pattern",
        "anterior injury pattern",
        "anterolateral injury pattern",
    ),
    "Cardiac hypertrophy / enlargement": (
        "left ventricular hypertrophy",
        "left atrial enlargement",
        "right ventricular hypertrophy",
        "right atrial enlargement",
        "biventricular hypertrophy",
        "biatrial enlargement",
    ),
    "Pacemaker related": (
        "electronic atrial pacemaker",
        "electronic ventricular pacemaker",
        "suspect unspecified pacemaker failure",
        "atrial tracking ventricular paced rhythm",
    ),
    "Specific patterns": (
        "undetermined rhythm",
        "digitalis effect",
        "pulmonary disease pattern",
        "acute pericarditis",
        "dextrocardia",
        "brugada pattern",
    ),
}
