seed: 0
development: true
num_cores: null # null uses the CPU count; set an integer to limit worker processes.
toy_dataset_fraction: null

save_path: /batch_data/heedb/preprocessed_250_10

target_sf: 250
segment_length: 10 # in seconds
